name: Static Check

on:
  pull_request:
  push:
    branches:
      - main
      - 1.*
jobs:
  CI:
    env:
      RUNNER_ALLOW_RUNASROOT: 1
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go-version: [ 1.19 ]
        runner: [ ubuntu, macos ]
      fail-fast: true
    steps:
      - name: prepare ubuntu environment
        if: matrix.runner == 'ubuntu'
        run: sudo apt-get clean && sudo apt-get update && sudo apt-get install -y libsystemd-dev

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Copy Lib
        if: matrix.runner == 'ubuntu'
        run: sudo cp ./pkg/logtail/libPluginAdapter.so /usr/lib/

      - name: Check License Header
        if: matrix.runner == 'ubuntu'
        run: make check-license

      - name: Check Dependencies Licences
        if: matrix.runner == 'ubuntu'
        run: make check-dependency-licenses

      # - name: Lint
      #   run: make lint

      - name: UnitTest
        run: sudo make unittest_plugin

      - name: UnitTest PluginManager
        run:  make unittest_pluginmanager

  result:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ CI ]
    steps:
      - name: Build Result
        run: echo "Just to make the GitHub merge button green"
